AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HostHeaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cf-github-ksi-host-header
      Runtime: nodejs22.x
      CodeUri: lambda/
      Handler: index.handler
      MemorySize: 128
      Timeout: 3
      AutoPublishAlias: live  # <- Required for versioning
      Policies:
        - Statement:
            - Effect: Allow
              Action: logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-1:880346748439:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:us-east-1:880346748439:log-group:/aws/lambda/*:*

Outputs:
  LambdaEdgeFunctionVersion:
    Description: "Lambda@Edge version ARN for CloudFront"
    Value: !Ref HostHeaderFunction.Version
    Export:
      Name: LambdaEdgeVersionArn
